### ISSUE TITLE
No connection to IRC

### ISSUE THREAD

**Issue by DE8MSH** [uwekamper/arduinoirc#1]
Hi,

I used your example of arduinoicr (Arduino Uno/Etherbetshield). But: even if I used a well known IRC server, I got no connection to it. Question: what is "USER  uk 8 *" mean?

Marco
DE8MSH

**Comment by uwekamper** [comment]
Hi,

I wrote this code a long time ago and haven't touched it since. It may be that public IRC servers (especially well known ones) have changed their rules regarding which clients they allow to connect. I used this code with one of the Freenode IRC servers. 

The line with "USER uk 8 *" contains the username/hostname etc. for the connection. For more information, see the RFC: https://tools.ietf.org/html/rfc2812#section-3.1.3

If you improve on this code, please feel free to fork it and/or send a pull request.
